codecov:
  allow_coverage_offsets: false

coverage:
  precision: 2
  round: down
  range: 70...100

  status:
    # Learn more at http://docs.codecov.io/docs/codecov-yaml
    project: true
      default:
        target: auto
        if_not_found: success
    patch: true
    changes: false

comment:
  layout: "header, diff, tree, changes, sunburst"
  require_changes: false
  branches: null
  behavior: default
  flags: null
  paths: null