spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: api-design
security:
  basic:
    enabled: false
  oauth2:
    resource:
      filter-order : 3

pagination:
  organization:
    default : 100
    max : 1000
  project :
    default : 100
    max : 1000
  assumption :
    default : 100
    max : 1000
  user :
    defailt : 100
    max : 1000

server:
  port: 9000

logging:
  level:
    org.springframework.web : debug

app:
  oauth:
    client-id: uNjKCwt2aH
    client-secret: X5QdJUHyWX