spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: api-design
security:
  basic:
    enabled: false

response:
  default:
    list:
      size : 10
  allowed:
    list:
      size: 100