spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: api-design
security:
  basic:
    enabled: false

pagination:
  organization:
    default : 10
    max : 100
  project :
    default : 10
    max : 100
  assumption :
    default : 10
    max : 1000
  user :
    defailt : 10
    max : 100