spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: api-design
security:
  basic:
    enabled: false

pagination:
  organization:
    default : 100
    max : 1000
  project :
    default : 100
    max : 1000
  assumption :
    default : 100
    max : 1000
  user :
    defailt : 100
    max : 1000

server:
  port: 9000
